name = "netexecs2025"
compatibility_date = "2024-05-11"

[env.production]
# Add your production environment variables here
# DATABASE_URL = "your_production_database_url"

[[r2_buckets]]
binding = "R2_netexec"
bucket_name = "R2_netexec"
# preview_bucket_name = "R2_netexec-preview" # Optional: for preview deployments

[site]
bucket = "dist/public"

[pages]
# This section is optional for Pages, but can be used for local dev
project = "netexecs2025" 